### ISSUE TITLE
unable to upload the file to aws

### ISSUE THREAD

**Issue by lokeshreddyp** [hjanuschka/fastlane-plugin-aws_device_farm#38]
Test upload failed. 🙈 .. Let me know if you need any additional info

getting this 

[20:38:37]: Preparing the upload to the device farm.
 
[20:38:38]: Uploading the application binary. ☕️
 
[20:38:44]: Uploading the test binary. ☕️
 
[20:38:47]: Waiting for the test upload to succeed. ☕️
 
and then 

Test upload failed. 🙈

 Any ideas on what's going on @hjanuschka

**Comment by lokeshreddyp** [comment]
here is the lane I have 

sh("chown -R $USER:everyone /Users/distiller/app")

       sh("mkdir -p /Users/distiller/app/aws-test")

       sh("cd /Users/distiller/app")

       sh("ls -l")

       sh("chmod 777 /Users/distiller/app/aws-test")

       sh("ls -l")

        # Build Test Runner Binary
        xcodebuild(
          clean: true,
          workspace: 'xxx.xcworkspace',
          scheme: 'xxx',
          destination: 'generic/platform=iOS',
          configuration: 'Development',
          derivedDataPath: '/Users/distiller/app/aws-test',
          xcargs: "ENABLE_BITCODE=NO ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -UseModernBuildSystem=NO build-for-testing"
        )

        sh("cd /Users/distiller/app/aws-test")

        sh("pwd")

        sh("ls")

        sh("mkdir -p packages/runner/Payload")

        sh("cd /Users/distiller/app/aws-test/Build/Products/Development-iphoneos/xxx-Runner.app; zip -r ../Payload.ipa .; cd -")

        ENV['FL_AWS_DEVICE_FARM_TEST_PATH'] = '/Users/distiller/app/aws-test/Build/Products/Development-iphoneos/Payload.ipa'

        sh("cd /Users/distiller/app/aws-test")

        sh("cd /Users/distiller/app/aws-test/Build/Products/Development-iphoneos/xxx.app; zip -r ../xxx.ipa .; cd -")

        ENV['FL_AWS_DEVICE_FARM_PATH'] = '/Users/distiller/app/aws-test/Build/Products/Development-iphoneos/xxx.ipa'

        sh("ls /Users/distiller/app/aws-test/Build/Products/Development-iphoneos/")

        sh("chmod -R 777 /Users/distiller/app/aws-test/Build/Products/Development-iphoneos/")
        
        sh("ls /Users/distiller/app/")

        sh("ls /Users/distiller/app/aws-test/")

        aws_device_farm(
          name:                "fastlane",
          binary_path:         "/Users/distiller/app/aws-test/Build/Products/Development-iphoneos/xxx.ipa",
          test_binary_path:    "/Users/distiller/app/aws-test/Build/Products/Development-iphoneos/xxx.ipa",
          device_pool:         "pool",
          wait_for_completion: true
        )

**Comment by lokeshreddyp** [comment]
here is some more info ..

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
Errno::EINVAL: [!] Invalid argument @ io_fread - /Users/distiller/app/aws-test/Build/Products/Development-iphoneos/AllTrailsAlpha.ipa
  /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-aws_device_farm-0.3.17/lib/fastlane/plugin/aws_device_farm/actions/aws_device_farm_action.rb:380:in `read'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-aws_device_farm-0.3.17/lib/fastlane/plugin/aws_device_farm/actions/aws_device_farm_action.rb:380:in `upload'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-aws_device_farm-0.3.17/lib/fastlane/plugin/aws_device_farm/actions/aws_device_farm_action.rb:29:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:177:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.148.1/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
